### PR TITLE
Add polymorphic deserialization for event account.

### LINKED ISSUE #1497: GHUser even when event comes from Organization type
**Describe the bug**
A `GHUser` type is returned even when in the payload the account type is `Organization`.

More precisely in the event `installation.created` when the `installation.account.type` is set to `Organization` (app installed in organization) the `installation.account` in the `@Installation.Created` payload returns a `GHUser`.

```yaml
{
  "action": "created",
  "installation": {
    "id": 12345,
    "account": {
      "login": "org-name",
      <...>
      "type": "Organization",
      "site_admin": false
    },
<...>
```

```kotlin
fun onInstall(@Installation.Created installationPayload: GHEventPayload.Installation) {
  val tenantGHOrganization = installationPayload.installation.account // <-- GHUser instance
}
```

Also tried to use the `installationPayload.organization` object but it always returned null (probably it's used in other events):

```kotlin
fun onInstall(@Installation.Created installationPayload: GHEventPayload.Installation) {
  LOG.info("org: " + installationPayload.organization.name) // <--  Cannot invoke "org.kohsuke.github.GHOrganization.getName()" because the return value of "org.kohsuke.github.GHEventPayload$Installation.getOrganization()" is null
}
```

**To Reproduce**
1. Create an event with `installation.created` in an organization (install app in an organization)
2. Catch the event
3. Retrieve the `installationPayload.installation.account` object
4. Or retrieve the `installationPayload.organization` object

**Expected behavior**
If the payload has the `installation.account.type` set to `Organization` the `installationPayload.installation.account`should return a GHOrganization object or the `installationPayload.organization` should not return null.

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.4 (Apple M1)

**Additional context**
Using Kotlin and [Quarkus GitHub App](https://github.com/quarkiverse/quarkus-github-app)

### PR DESCRIPTION
**Pull request by bloslo**
# Description

Add polymorphic deserialization for the `GHAppInstallation` `account` field.
Fixes #1497

# Before submitting a PR:

- [ ] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [ ] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [ ] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [ ] Fill in the "Description" above with clear summary of the changes. This includes:
  - [ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [ ] Enable "Allow edits from maintainers".

### CODE REVIEW

**Comment by bloslo** [comment]
@bitwiseman Can you review my changes? I know checks are breaking, but this is because I change a method signature. I don't see how this can be avoided.

P.S. I used the StackOverflow link you referenced in the issue as a source to implement the changes.

**Comment by bitwiseman** [comment]
@bloslo 
To address API breaks, you'll need to use `WithBridgeMethods` annotations. They preserve binary compatibility while letting you update the source API. Usage is described in the [source file](https://github.com/infradna/bridge-method-injector/blob/master/annotation/src/main/java/com/infradna/tool/bridge_method_injector/WithBridgeMethods.java) and there are plenty of examples in this project.

**Review by bitwiseman — CHANGES_REQUESTED** [review]
Changes look good, nicely done! 

Add bridge methods to fix API breaks. The bridge will need to be a custom conversion method. And you'll need to add a test that makes sure the scenario where someone calls the old `GHUser` method when the instance is now a`GHOrganization` still works the same as before. You don't have to improve the behavior, just make sure it isn't any more broken.

**Comment by Haarolean** [comment]
@bitwiseman is there a chance to get this merged in?

**Comment by bitwiseman** [comment]
@Haarolean 
See my previous comment.   There are API breaking changes that need to be addressed (using bridge methods) before this can be merged.

**Comment by anujhydrabadi** [comment]
@bitwiseman any chance we can have this in the 2.x release? I'm happy to recover this PR and re-test or re-implement if needed, but looks complete otherwise, as we do not need to worry about backward compatibility.

**Comment by bitwiseman** [comment]
@anujhydrabadi 
Please proceed.

**Pull request closed without merging**
