### PR TITLE
add org filter to repository search

### PR DESCRIPTION
**Pull request by jetersen**
# Description

add org filter to repository search

https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-within-a-users-or-organizations-repositories

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [x] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Review by bitwiseman — CHANGES_REQUESTED** [review]
@jetersen 
Please complete the PR checklist (updated the PR description to include it). 

In particular, add this parameter to an existing test or create new tests for it.

**Comment by jetersen** [comment]
@bitwiseman I couldn't find any existing tests that used the repository search feature 😓

**Comment by bitwiseman** [comment]
@jetersen 
Take a look at https://github.com/hub4j/github-api/pull/1188

**Comment by bitwiseman** [comment]
@jetersen 
Do you have time to update this PR?  I'll be doing a release in the next few days. This just needs test coverage.

**Comment by jetersen** [comment]
@bitwiseman test are added 😅

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
