### PR TITLE
Fix `GHFileNotFoundException` when getting commits from PR found in search

### LINKED ISSUE #1778: Asking for a list of commits from a PR that has been a sourced from a search results in GHFileNotFoundException
**Describe the bug**

Hello.

I'm writing a test program to evaluate the library:

```java
package org.example;

import org.kohsuke.github.*;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello world from Github API Experiment!");
        String token = "xxx";

        try {
            // Connect
            GitHub github = new GitHubBuilder().withOAuthToken(token).build();
            System.out.println("Built Github API bridge");
            System.out.println("With valid credential: " + github.isCredentialValid());

            // Get ref from environment
            String ref_name = System.getenv("GITHUB_REF_NAME");
            System.out.println("Ref name is " + ref_name);

            GHRepository repo = github.getRepository("NlightNFotis/demo-spring-petclinic");

            // Create branch out of ref
            GHBranch pr_branch = repo.getBranch(ref_name);

            // Find pull request corresponding to ref
            GHPullRequestSearchBuilder builder = repo.searchPullRequests().isOpen();
            var pr_list = builder.list();
            System.out.println("PRs found " + pr_list.getTotalCount());

            // Iterate through PRs
            for (var pr : pr_list) {
                System.out.println("PR URL: " + pr.listCommits().toArray()[0].getUrl());
            }
        } catch (Exception e) {
            System.out.println("Got an exception: " + e.getMessage());
        }
    }
}
```

This unfortunately results in a 404 from Github's endpoint, with the output being the following:

```
Hello world from Github API Experiment!
Built Github API bridge
With valid credential: true
Ref name is cover_action
PRs found 1
Got an exception: https://api.github.com/repos/NlightNFotis/demo-spring-petclinic/issues/1/commits {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
```

The error that shows up is a `GHFileNotFoundException`.

I spent some time trying to debug it, and I understand that the issue is because of the `/issues/` path in the URL being queried. If I change the URL to point to `/pulls/` instead of `/issues/` in a debugger, the issue vanishes: `https://api.github.com/repos/NlightNFotis/demo-spring-petclinic/pulls/1/commits`.

I have managed to identify the culprit as the `GHPullRequest.getApiRoute` method.

```java
/**
     * Gets the api route.
     *
     * @return the api route
     */
    @Override
    protected String getApiRoute() {
        if (owner == null) {
            // Issues returned from search to do not have an owner. Attempt to use url.
            final URL url = Objects.requireNonNull(getUrl(), "Missing instance URL!");
            return StringUtils.prependIfMissing(url.toString().replace(root().getApiUrl(), ""), "/");
        }
        return "/repos/" + owner.getOwnerName() + "/" + owner.getName() + "/pulls/" + number;
    }
```

What I understand about the issue is:

1. In my code, I retrieve pull requests using a search. This results in objects that have no `owner`.
2. Inside of `GHPullRequest.getApiRoute`, the `owner == null` path is being followed, trying to compensate for the lack of an owner by trying to get an API URL from previous API responses.
3. This results in a URL that contains the `/issues/` path, e.g. `repos/NlightNFotis/demo-sping-petclinic/issues/`, which is then appended to by other queries, such as `listCommits()`.
4. The request is then sent to GitHub, resulting in a 404.

**Expected behavior**

If I build with a patched version locally, I get the (expected) output of:

```
Hello world from Github API Experiment!
Built Github API bridge
With valid credential: true
Ref name is cover_action
PRs found 1
PR URL: https://github.com/NlightNFotis/demo-spring-petclinic/commit/c0b514d30b11a03dbaea71cebec4d4f6cad0f45a
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Sonoma 14.0
 - Browser [e.g. chrome, safari] Safari 17.0
 - Version [e.g. 22] 1.319

**Additional context**

I have a fix and a regression test locally that I will try to push. It's a drive by change, so I don't know if it satisfies the quality standards of the project, though I have taken every care to try to meet them.

### PR DESCRIPTION
**Pull request by NlightNFotis**
# Description

Fixes #1778.

The issue summarily was that a compensation mechanism for sourcing a URL for a query was generating the wrong URL, that was then being used by other parts of the library to create further queries that the Github API would then reject.

This fixes the issue by doing a string search and replace after the string has been first sourced. It has been observed locally that this is an effective fix for the issue described.

Please consider the above a proposed change. If the project maintainers think that this is not an appropriate fix, I'm happy to rework this (if minor changes are needed) or close the PR (if major changes are needed, that are better to be done by someone more familiar with the codebase than myself).

Thank you,

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments explaining the behavior. 
- [ ] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [ ] Fill in the "Description" above with clear summary of the changes. This includes:
  - [ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Review by bitwiseman — APPROVED** [review]
Looks good to me and has test coverage. Thanks!

**Comment by daniel-b2c2** [comment]
I think this issue might still linger? I can't retrieve `getMergeableState` from `GHPullRequest` which appears to be calling `https://api.github.com/repos/owner/repo/issues/10312` I don't think this is correct. The API endpoint should be /pulls/

**Comment by bitwiseman** [comment]
Please provide details. Maybe sample code that reproduces this. Are you on the most recent version.

**Comment by daniel-b2c2** [comment]
Sure, thanks for taking the time to look, see below:

pom.xml showing latest version:

```
        <dependency>
            <groupId>org.kohsuke</groupId>
            <artifactId>github-api</artifactId>
            <version>1.319</version>
        </dependency>
```


Main body of code to demonstrate issue

```
        GHRepository repository = github.getRepository("b2c2/" + Repo.APP_CONFIG.getProjectName());
        GHPullRequestSearchBuilder query = repository.searchPullRequests();
        PagedSearchIterable<GHPullRequest> list = query.isOpen().list();
        GHPullRequest candidatePullRequests = list.toList().get(0);
        candidatePullRequests.getMergeable();
        String mergeableState = candidatePullRequests.getMergeableState(); // see screenshots for call sequence to incorrect URI
        System.out.println(mergeableState);
```

Screenshot 2024-02-27 at 11 56 30
Screenshot 2024-02-27 at 11 56 43
Screenshot 2024-02-27 at 11 56 57

**Comment by gsmet** [comment]
Yeah, the problem is that we are using `getUrl()` in `refresh()` and as demonstrated in `getApiRoute()`, it's not safe for pull requests.

My understanding is that we should use `getApiRoute()` instead.

**Comment by daniel-b2c2** [comment]
So the pattern of using refresh() is fine, it's just the usage of getUrl, should be replaced with getApiRoute?

**Comment by gsmet** [comment]
Yes, that's what I would do. Would you be able to prepare a PR? Ideally with a test case?

**Comment by gsmet** [comment]
@daniel-b2c2 I created https://github.com/hub4j/github-api/pull/1810 to fix it. Thanks for providing all the details.

**Pull request merged**
