### PR TITLE
Update GHEvent.java

### LINKED ISSUE #1234: GHEvent is missing new events that is breaking Jenkins plugin usage
**Describe the bug**
Getting error:
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.kohsuke.github.GHEvent` from String "merge_queue_entry": not one of the values accepted for Enum class: [GOLLUM, ALL, INTEGRATION_INSTALLATION_REPOSITORIES, META, DOWNLOAD, FORK_APPLY, CHECK_RUN, MARKETPLACE_PURCHASE, PROJECT_CARD, PUSH, PAGE_BUILD, TEAM_ADD, REPOSITORY_VULNERABILITY_ALERT, PACKAGE, DELETE, DEPLOYMENT_STATUS, WATCH, FOLLOW, ORG_BLOCK, ORGANIZATION, COMMIT_COMMENT, ISSUE_COMMENT, REPOSITORY_IMPORT, GITHUB_APP_AUTHORIZATION, CODE_SCANNING_ALERT, CHECK_SUITE, FORK, GIST, CONTENT_REFERENCE, REPOSITORY, INSTALLATION_REPOSITORIES, REPOSITORY_DISPATCH, MILESTONE, STAR, LABEL, MEMBERSHIP, SECURITY_ADVISORY, PROJECT_COLUMN, TEAM, PULL_REQUEST_REVIEW, RELEASE, PUBLIC, WORKFLOW_RUN, STATUS, PULL_REQUEST, PROJECT, WORKFLOW_DISPATCH, CREATE, MEMBER, REGISTRY_PACKAGE, INSTALLATION, DEPLOYMENT, PULL_REQUEST_REVIEW_COMMENT, DEPLOY_KEY, PING, ISSUES]
 at [Source: (String)"[{"id":......
```

When trying to connect to github app from jenkins.

**To Reproduce**
1. Set up Jenkins Github App
2. No event subscriptions are needed as this occurs even when nothing is selected
3. Start creating a new Github App Credential in jenkins 
4. Once all the fields are set hit `Test` to test the connection 
5. It should fail with the above error

**Expected behavior**
Jenkins Github App Connectivity should work with new events

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version latest

**Additional context**
Create this PR with possible fix and more info https://github.com/hub4j/github-api/pull/1233

Creating this issue as I was unsure if the PR was enough and also for visibility

### PR DESCRIPTION
**Pull request by philippebailer**
# Description

Seems we are rehashing this issue: https://issues.jenkins.io/browse/JENKINS-63348

Which was fixed by @bitwiseman with this https://github.com/hub4j/github-api/pull/911

I'm similarly adding `Pull request review thread` and `Merge queue entry` events to avoid breaking auth as unlike the previous ticket unsubscribing from `Merge queue entry` does not seem to work. These events seem to be new since I have found no documentation on them at [webhooks-and-events](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)

We just finished setting up the github app yesterday to have it break a few hrs later with the merge event error so I assume some change regarding that event was released at that time.

Idk if its possible to get this change merged and pushed through to a new version of github-api-plugin but our jenkins integration setup is currently blocked by this. Please let me know if there is anything I can do to help move this along.

Thanks you!

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time.

- [x] Push your changes to a branch other than `main`. Create your PR from that branch.
- [x] Add JavaDocs and other comments
- [x] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.

# When creating a PR: 

- [x] Fill in the "Description" above.
- [x] Enable "Allow edits from maintainers".

Closes #1234

### CODE REVIEW

**Comment by philippebailer** [comment]
For some additional data the errors I've experienced are:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.kohsuke.github.GHEvent` from String "pull_request_review_thread": not one of the values accepted for Enum class: [GOLLUM, ALL, INTEGRATION_INSTALLATION_REPOSITORIES, META, DOWNLOAD, FORK_APPLY, CHECK_RUN, MARKETPLACE_PURCHASE, PROJECT_CARD, PUSH, PAGE_BUILD, TEAM_ADD, REPOSITORY_VULNERABILITY_ALERT, PACKAGE, DELETE, DEPLOYMENT_STATUS, WATCH, FOLLOW, ORG_BLOCK, ORGANIZATION, COMMIT_COMMENT, ISSUE_COMMENT, REPOSITORY_IMPORT, GITHUB_APP_AUTHORIZATION, CODE_SCANNING_ALERT, CHECK_SUITE, FORK, GIST, CONTENT_REFERENCE, REPOSITORY, INSTALLATION_REPOSITORIES, REPOSITORY_DISPATCH, MILESTONE, STAR, LABEL, MEMBERSHIP, SECURITY_ADVISORY, PROJECT_COLUMN, TEAM, PULL_REQUEST_REVIEW, RELEASE, PUBLIC, WORKFLOW_RUN, STATUS, PULL_REQUEST, PROJECT, WORKFLOW_DISPATCH, CREATE, MEMBER, REGISTRY_PACKAGE, INSTALLATION, DEPLOYMENT, PULL_REQUEST_REVIEW_COMMENT, DEPLOY_KEY, PING, ISSUES]
 at [Source: (String)"{"id":....
```

and 

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.kohsuke.github.GHEvent` from String "merge_queue_entry": not one of the values accepted for Enum class: [GOLLUM, ALL, INTEGRATION_INSTALLATION_REPOSITORIES, META, DOWNLOAD, FORK_APPLY, CHECK_RUN, MARKETPLACE_PURCHASE, PROJECT_CARD, PUSH, PAGE_BUILD, TEAM_ADD, REPOSITORY_VULNERABILITY_ALERT, PACKAGE, DELETE, DEPLOYMENT_STATUS, WATCH, FOLLOW, ORG_BLOCK, ORGANIZATION, COMMIT_COMMENT, ISSUE_COMMENT, REPOSITORY_IMPORT, GITHUB_APP_AUTHORIZATION, CODE_SCANNING_ALERT, CHECK_SUITE, FORK, GIST, CONTENT_REFERENCE, REPOSITORY, INSTALLATION_REPOSITORIES, REPOSITORY_DISPATCH, MILESTONE, STAR, LABEL, MEMBERSHIP, SECURITY_ADVISORY, PROJECT_COLUMN, TEAM, PULL_REQUEST_REVIEW, RELEASE, PUBLIC, WORKFLOW_RUN, STATUS, PULL_REQUEST, PROJECT, WORKFLOW_DISPATCH, CREATE, MEMBER, REGISTRY_PACKAGE, INSTALLATION, DEPLOYMENT, PULL_REQUEST_REVIEW_COMMENT, DEPLOY_KEY, PING, ISSUES]
 at [Source: (String)"[{"id":......
```

I can reproduce the `merge_queue_entry` error regardless of what events are selected, even no event subscriptions will generate the above error and block the jenkins plugin from continuing

**Comment by philippebailer** [comment]
It would also be great to just support unknown values as shown [here](https://stackoverflow.com/questions/29163190/jackson-ignore-unknown-enum-values)

Mapper change at [GitHubClient](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GitHubClient.java#L68)
```
MAPPER.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE, true);
```

Enum change at [GHEvent](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GHEvent.java#L75)
```
@JsonEnumDefaultValue 
UNKNOWN
```

If the above seems fine I can open another PR with those changes to see if any tests run into issues.

I don't want to make this change in this PR since I really just want to get my integration working and the above solution seems like the most straight forward option.

**Review by nicolt — APPROVED** [review]

**Comment by philippebailer** [comment]
Closes #1234

**Comment by bitwiseman** [comment]
> It would also be great to just support unknown values as shown [here](https://stackoverflow.com/questions/29163190/jackson-ignore-unknown-enum-values)
> 
> Mapper change at [GitHubClient](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GitHubClient.java#L68)
> 
> ```
> MAPPER.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE, true);
> ```
> 
> Enum change at [GHEvent](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GHEvent.java#L75)
> 
> ```
> @JsonEnumDefaultValue 
> UNKNOWN
> ```
> 
> If the above seems fine I can open another PR with those changes to see if any tests run into issues.
> 
> I don't want to make this change in this PR since I really just want to get my integration working and the above solution seems like the most straight forward option.

@philippebailer 
We chose to go a different direction. Instead of serializing directly enum, we've moved to serializing to string and the converting to enum on read.  This perserves the returned value for analysis if needed.

**Pull request merged**
