### PR TITLE
Adds methods to GHRepository to get the top ten referral paths and referrers via the API

### PR DESCRIPTION
**Pull request by ihrigb**
# Description

Adds methods to `GHRepository` to get the top ten referral paths and referrers via the API.

References:
- https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-top-referral-paths
- https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-top-referral-sources

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments explaining the behavior. 
- [x] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [ ] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [x] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Comment by ihrigb** [comment]
Maybe someone could help with tests here. I get `No response could be served as there are no stub mappings in this WireMock instance.`.

**Comment by bitwiseman** [comment]
What failure are you getting on `main`?

**Comment by ihrigb** [comment]
@bitwiseman ?

**Comment by ihrigb** [comment]
@bitwiseman ping again

**Comment by bitwiseman** [comment]
@ihrigb 
To make the tests run locally, run this:

```
mvn -B clean install -D enable-ci "-Dsurefire.argLine=--add-opens java.base/java.net=ALL-UNNAMED"
```

I understand this differs from what is in `CONTRIBUTING.md`. I'm working on updating the build and the instructions to remove the need for that extra argument.

**Comment by ihrigb** [comment]
In that case, the build is fine.

**Comment by bitwiseman** [comment]
@ihrigb 
It looks like there are still some CI failures.  Please update this PR.

**Comment by ihrigb** [comment]
@bitwiseman should be good now...

**Comment by bitwiseman** [comment]
@ihrigb 
Sorry, code coverage reporting was broken for a bit.  Now it is working, please address items in the report.

**Comment by ihrigb** [comment]
@bitwiseman can you please grant me access to `hub4j-test-org`?

**Comment by ihrigb** [comment]
@bitwiseman finally ready to merge.

**Review by bitwiseman — APPROVED** [review]

**Comment by bitwiseman** [comment]
You got reasonable tests without needing test-org access.  Thanks for sticking with this!

**Comment by ihrigb** [comment]
> You got reasonable tests without needing test-org access. Thanks for sticking with this!

Is that preferrable over using the test org?

**Comment by bitwiseman** [comment]
No, test org is generally better for future test support, but wanted to get your change into this release.

**Comment by ihrigb** [comment]
@bitwiseman I did get the invitation mail for the test org, but seems like the invitation itself does no longer exist.

**Comment by bitwiseman** [comment]
@ihrigb 
Resent invitation, so you have it for what ever your next PR is.

**Comment by ihrigb** [comment]
Rulesets (#1181) ;)
Thanks!

**Pull request merged**
