### PR TITLE
Added startup failure to the Conclusion enum class and added test acc…

### PR DESCRIPTION
**Pull request by yasin-herken**
Fixes#Unknown value startup_failure #1722
I added startup_failures to the Conclusion enum class and wrote a test but I couldn't figure out what GitHub workflows have with conclusion startup_failures so I wrote a test which has 0 length but if I can add workflow that has startup failures, I can change the test result.

### CODE REVIEW

**Review by bitwiseman — CHANGES_REQUESTED** [review]
@yasin-herken 
Thanks for the PR!

Please review the steps in the contributing for how to record data for a new test.  I've invited you to the `hub4j-test-org` to enable that.  Then you can do whatever you need to create a workflow that fails to start and records a result for that.

**Comment by yasin-herken** [comment]
I have added the startup-failure workflow however, I couldn't get the `startup-failure ` conclusion. I am getting `failure` conclusion, how to create workflow that has `startup-failure` conclusion

**Comment by bitwiseman** [comment]
@yasin-herken 
Record the test with the the failure conclusion. Then manually edit the recorded JSON to have `startup-failure` instead of `failure`.  Then add `snapshotNotAllowed()` to the top of the test method to ensure it isn't accidentally re-recorded later.

**Comment by yasin-herken** [comment]
Fixes#Unknown value startup_failure https://github.com/hub4j/github-api/issues/1722
I added startup_failures to the Conclusion enum class and wrote a test for it.

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
