### PR TITLE
Includes template_repository information fixes #1549

### LINKED ISSUE #1549: Feature Request: Get template repo details from created repository
It would be great to be able to get the template repository details from a created repo - so you could know what repository the created repo is based off.

This information is available through the rest API. 

Example on a simple GET request to https://api.github.com/repos/org/reponame - I would love to expose the template_repository json object

{
    "id":xxxx,
    "node_id": "R_kgDOIQCw0A",
    "name": "test-generic-repo",
    "full_name": "orgt/test-generic-repo",
    "private": true,
    "**template_repository**": {
        "id": 470521023,
        "node_id": "R_kgDOHAuUvw",
        "name": "my-template",
        "full_name": "org/my-template",
        "private": true,
        "owner": {
            "login": "org",
            "id": 69310803,
            "avatar_url": "https://avatars.githubusercontent.com/u/69310803?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/org",
            "html_url": "https://github.com/org",
            "followers_url": "https://api.github.com/users/org/followers",
            "following_url": "https://api.github.com/users/org/following{/other_user}",
            "gists_url": "https://api.github.com/users/org/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/org/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/orgt/subscriptions",
            "organizations_url": "https://api.github.com/users/org/orgs",
            "repos_url": "https://api.github.com/users/org/repos",
            "events_url": "https://api.github.com/users/org/events{/privacy}",
            "received_events_url": "https://api.github.com/users/org/received_events",
            "type": "Organization",
            "site_admin": false
        }
    "network_count": 0,
    "subscribers_count": 0
}

### PR DESCRIPTION
**Pull request by robinvandenbogaard**
# Description

Include template repository in detailed representations. Fixes #1549 
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-teams

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [x] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.
- [x] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Review by bitwiseman — CHANGES_REQUESTED** [review]
Please fix CI failures.

**Comment by robinvandenbogaard** [comment]
Added the missing javadoc. I was using the wrong jdk for the `mvn -D enable-ci clean install site` to pass last month. It passes now locally.

**Comment by robinvandenbogaard** [comment]
#1604 wrongfully closed this PR, it so happens to share the number 1579 with an identically numbered issue.

The fix in this PR still needs to be applied, please reopen.

**Comment by bitwiseman** [comment]
@robinvandenbogaard 
Looks like we still need more tests.

**Pull request closed without merging**
