### PR TITLE
Fix Issue #576 collaborator by username

### LINKED ISSUE #576: Does the github api support getting a collaborator by username?
Is the following API supported?

GET /repos/:owner/:repo/collaborators/:username

https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator

Also does collaborator just imply a user that has write access?

I looked at the code but i'm not seeing it in the GHRepository.java file.  Wanted to verify if I was just not seeing it?

Thanks,
Derek

### PR DESCRIPTION
**Pull request by 0xacx**
# Description

Fixes #576
 Adds a method to check if GHUser is a collaborator on that repository. You can find the github documentation for that endpoint [here](https://docs.github.com/en/rest/reference/collaborators#check-if-a-user-is-a-repository-collaborator=). 

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [x] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.
- [x] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Comment by 0xacx** [comment]
When I run the tests with `mvn -D enable-ci clean install site` the new test fails locally as the mock response is missing. Could you please invite me to the test org or is there another way I could mock that response?

**Comment by axilleasx** [comment]
Hi! Could I please have access to the test org so I can record the response for the wiremock stub? 
Thank you!

**Comment by 0xacx** [comment]
@bitwiseman Could I please have access to the test org so I can record the response for the wiremock stub?
Thank you!

**Comment by bitwiseman** [comment]
@0xacx Invitation sent.

**Comment by 0xacx** [comment]
@bitwiseman Unfortunately I haven't logged in for a long while and the invitation expired. Any chance you could resend it? 
Thanks!

**Comment by bitwiseman** [comment]
@0xacx Sent invite again.

**Comment by 0xacx** [comment]
@bitwiseman The Java 8 build is failing at the codecov job, because of an expired certificate. It looks random to me, as if it was indeed expired, all branches should suffer from that. Could we try a rerun or is there something else I should do?

**Comment by bitwiseman** [comment]
Nothing for you to do right now. I'll get it fixed up and rerun.

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
