### PR TITLE
Generify OrgAppInstallationAuthorizationProvider to support any kind of app lookup.

### PR DESCRIPTION
**Pull request by PierreBtz**
# Description

The `OrgAppInstallationAuthorizationProvider` only works with organization level apps, leaving out user apps. The bulk of the class logic remains useful to perform application lookup other ways (eg using the installation id), or even to lookup for user application.

This PR provides a way for the API user to provide its own lookup logic.

This PR is submitted as a draft because:
* I would need access to the `hub4j-test-org` as well as the installation id of the test app to finish writing the tests.
* I'm not 100% convinced `OrgAppInstallationAuthorizationProvider` should be deprecated. The way I see it, it's not useless and just a maintenance burden that you might want to remove in the future after a deprecation phase :)

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments as appropriate. Consider including links in comments to relevant documentation on https://docs.github.com/en/rest .  
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
- ~[ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue.~ 
- ~[ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible.~
- [x] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Comment by PierreBtz** [comment]
@bitwiseman thanks for the access. I finally had time to complete this work...

**Comment by PierreBtz** [comment]
@bitwiseman gentle ping, is there anything blocking this PR from being merged? Thanks for your time.

**Review by bitwiseman — APPROVED** [review]

**Comment by bitwiseman** [comment]
@PierreBtz 
I'll get in the next day.

**Comment by bitwiseman** [comment]
https://github.com/hub4j/github-api/releases/tag/github-api-1.315

**Comment by PierreBtz** [comment]
Thanks!!

**Pull request merged**
