### PR TITLE
Add GHOrganization.listSecurityManagers()

### PR DESCRIPTION
**Pull request by kozmic**
# Description

Add support to list [Security Managers](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization) in a GitHub Organization. See [GitHub's API doc for this API](https://docs.github.com/en/rest/orgs/security-managers?apiVersion=2022-11-28#list-security-manager-teams) for more details about this API.

## Tests:
If I'm given access to the `hub4j-test-org` Org, including permission to create a team and configure that team as a Security Manager team (or someone else can set this  up for me), I can include an integration test (I didn't find a step-by-step process in CONTRIBUTING.md to get this access. 

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments explaining the behavior. 
- [ ] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [ ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ ] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [ ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Review by muhammedabdelkader — APPROVED** [review]
LGTM!

**Review by muhammedabdelkader — APPROVED** [review]

**Review by bitwiseman — CHANGES_REQUESTED** [review]
Please add a test for CI.

**Comment by kozmic** [comment]
@bitwiseman : I would love to, but you need to add me to the test org so I can add a security maanger to run the tests against. Or is a unit test good enough for you?

From the description of this PR:
> If I'm given access to the hub4j-test-org Org, including permission to create a team and configure that team as a Security Manager team (or someone else can set this up for me), I can include an integration test (I didn't find a step-by-step process in CONTRIBUTING.md to get this access.

**Comment by kozmic** [comment]
@bitwiseman : I've added test response files that I've manually created and created unit tests based on those. Let me know if you want me to have real files from your test org, then you need to add me with permission to add a security team to the test org (or you can do it, and give me read access).

**Comment by kozmic** [comment]
@bitwiseman : Could you take a look at this?

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
