### PR TITLE
Replace reflection with X-HTTP-Method-Override

### LINKED ISSUE #754: Illegal Reflective Access Operation to field java.net.HttpURLConnection.method
**Describe the bug**
I attempt to archive a repository using the following code:
```java
GHRepository repo = this.org.getRepository("repo-name-here");
repo.archive();
```
When checking GitHub itself, the repository is in fact archived, however I receive a warning in the stderr stream consisting of the following:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo (file:/C:/Users/andrew/.m2/repository/org/kohsuke/github-api/1.108/github-api-1.108.jar) to field java.net.HttpURLConnection.method
WARNING: Please consider reporting this to the maintainers of org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**To Reproduce**
1. Fetch a `GHRepository` that is not yet archived.
2. Call `archive()` on that repository.

**Expected behavior**
I expect that there should not be any illegal reflective access exceptions.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 74

### PR DESCRIPTION
**Pull request by bitwiseman**
# Description 

To workaround the limitation where `HttpURLConnection` does not support `PATCH` method, the library was using reflection to change the method string.  This involved quite a bit of hackery. 

This change replaces all that with the `X-HTTP-Method-Override`. 

Tested with a few API calls and but mostly manually updated test resources.

Fixes #754

@aalmiray 

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time. 

- [x] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [x] Add JavaDocs and other comments
- [x] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI. 

# When creating a PR: 

- [x] Fill in the "Description" above. 
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Comment by bitwiseman** [comment]
@gsmet Heads up, if you are using the built-in HttpConnector in your systems as opposed to okttp3.OkHttpConnector this may effect your tests. The product change should be transparent to end-users but test systems that Wiremock and expect specific requests will detect the difference.

**Comment by gsmet** [comment]
Thanks for the heads up. I don't use the HttpConnector in production as this dark magic reflection thingy didn't work in native mode with GraalVM so that's a good thing it's gone! But sure my tests will be affected.

**Review by timja — APPROVED** [review]
could look at a multi release jar and using the built in modern http client at some point as well

**Comment by gsmet** [comment]
@bitwiseman any chance you could release a new version? I start seeing complaints about this from people trying JDK 16.

**Pull request merged**
